import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fcf8f8",
        "on-primary-fixed-variant": "#464747",
        "inverse-primary": "#c7c6c6",
        "outline-variant": "#c4c7c7",
        "background": "#fcf8f8",
        "primary-fixed-dim": "#c7c6c6",
        "on-error": "#ffffff",
        "tertiary-container": "#1e1b1b",
        "primary-container": "#1b1c1c",
        "surface-tint": "#5e5e5e",
        "on-primary-container": "#848483",
        "on-tertiary-container": "#888382",
        "on-background": "#1c1b1b",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "inverse-surface": "#313030",
        "surface-bright": "#fcf8f8",
        "surface-variant": "#e5e2e1",
        "primary-fixed": "#e3e2e1",
        "on-surface": "#1c1b1b",
        "surface-dim": "#ddd9d8",
        "error": "#ba1a1a",
        "on-secondary-container": "#fefcff",
        "secondary-container": "#2469ff",
        "inverse-on-surface": "#f4f0ef",
        "on-tertiary-fixed": "#1e1b1b",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container": "#f1edec",
        "surface-container-low": "#f7f3f2",
        "on-surface-variant": "#444747",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#003da9",
        "primary": "#000000",
        "on-primary-fixed": "#1b1c1c",
        "secondary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#ccc5c4",
        "on-tertiary-fixed-variant": "#4a4646",
        "surface-container-high": "#ebe7e7",
        "on-secondary-fixed": "#00174c",
        "secondary": "#0050d7",
        "outline": "#747878",
        "tertiary": "#000000",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        lg: "48px",
        unit: "4px",
        gutter: "24px",
        xs: "8px",
        xl: "80px",
        "container-margin": "24px",
        md: "24px",
        sm: "16px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "numeric-data": ["Inter"],
        "display-xl": ["Inter"],
        "label-sm": ["Inter"],
        "display-lg": ["Inter"],
        "heading-md": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "numeric-data": ["24px", { lineHeight: "1.0", letterSpacing: "-0.055em", fontWeight: "500" }],
        "display-xl": ["82px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }],
        "heading-md": ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
